# Generated by Django 5.0.4 on 2025-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('mssv', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('khoa', models.CharField(choices=[('cntt', 'Công nghệ thông tin'), ('ck', 'Cơ khí'), ('dt', 'Điện tử')], max_length=10)),
                ('math', models.FloatField()),
                ('physics', models.FloatField()),
                ('chemistry', models.FloatField()),
            ],
        ),
    ]
